dist: precise
sudo: false
language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  app: yose-nodejs
  api_key:
    secure: NQbMaaiN1yqXHJZ7sF97XyWySPf/HFwny/aY8aCA/QIHi0hCzQUG9ltkk4TTj4bABuHtYGDw+jHYAO20372n37208uo0wbiB4Nkuje9ELr5VpNgDA9lyijmEVaLLKdulCzD+Kh3NBT9eD95T3u9m5u1Kbzh1h8+0s3kHfHUUwGMG5V606IfhrO2aA2G+/gu4zE8wJJMxlLcCFZoVa+YHR/7BfDoq5+qTNHK1sTcLK0ZXMNlgT9O2mZDLYyKHBHtyce1InKlz7TY1QFjOpR3rvuNCEWbGROkFj1zLb2TtneIHS5if9L2O9KntslBvrRu3i2Bljm+dzYsoRC0C58d9nSVRWq2BS/HHVIZuufyKQxT7VTS2yeNF0LrLnnIFhoKaoDEZqMrU/jwQLKAkbKfnhtod+DJ9AZJiCMWBGSeNfhmhUr4/NvZTKdya8C4dpquFf+LMx2igkLw8wCO/yIpULAdw8Wkg0vXjj5op88zccjhrh78pg/xYFKm7XIAdwinf4JbBePNgIlRoigjLhZB+CpjW5TqnpEq7UkOopBQKi8266FNvmsXuNmjkUWxblN8K1Gu/1f8IVmm2tzsaNi5UoB/muQ04RHQFdJJLiQE9oeDnS01f8rbGU5EoeTsglL62NwrzYPkIzrv8HnkAAw6A3BCoEshkDe0X9Y53hmYQRD0=
