language: node_js
node_js:
  - "7"
deploy:
  provider: heroku
  app: yose-nodejs
  api_key:
    secure: XK+mG0QaIYsIfM1r9CrdrttyUdyPZsqcK5HG3I4M/4uSV23wK3LlYyeNUGiLw0Moz/MOrjX5HN1maqsQaIpGYJ1Qb3ioaXGHWuCpTJH6KEEfTs5xpXrfUoIsh8toqJRW0ArYo5AsRLNUnqN5sie5XTvZ5LHaqsucu1vR3HqWApZgqOuOvd0IFI1DNaWHb7OT92Ca1DG0faA8H9ghJRPLwy9/K9ow03RNGglpfsXwK4dxzeWFFv4kCNk9LzicYznX5b6rzK5A4O5ETBPfaPmEv5qLuAlCvtiEWUqosFhNKsevc31kJ0aw+HxFdED5rvpG7v2bZumoc6xQSX/HnjxNLziUzC3o4NlgijH8l68Fk5d50til+JlVaRNnVTMb6wuAjqtBqw6DrMs05WBc4Czk3+v1uzpE4xZEmlw4f0MPfLTDI0Ttql55vlYueIXgXx/6xnhUxu3Ops9DxVZuJTglUvKa2JtUqNL76DL1ebO5hrUeM+lfZrJcFRvWWkUPcL0HD/0YUBsJLbcaUEfDomWj4jLJuHxMRGWbLa2y5KP4NCFfua3fyK01fxcVc/V6oscw4/7v7ayOchGOks1ukM34cmW6oy6ELlRpgJw9KMApqGkRDVWFbeYhrQblhAshr+Om+xF73uN/LBjDC3vrdKrMx/6OVG3VhT4jNNGnKyUg9Ls=
